package com.iexec.common.replicate;

public enum ReplicateStatusCause {

    // chain
    CHAIN_UNREACHABLE,
    CHAIN_UNSYNCHRONIZED,
    BLOCK_NOT_REACHED,
    STAKE_TOO_LOW,
    OUT_OF_GAS,
    TASK_NOT_ACTIVE,
    TASK_DESCRIPTION_NOT_FOUND,
    CONTRIBUTION_ALREADY_SET,
    CONSENSUS_REACHED,
    CHAIN_RECEIPT_NOT_VALID,
    CONSENSUS_BLOCK_MISSING,

    // computation
    TEE_NOT_SUPPORTED,
    APP_NOT_FOUND_LOCALLY,
    DETERMINISM_HASH_NOT_FOUND,
    ENCLAVE_SIGNATURE_NOT_FOUND,
    TEE_EXECUTION_NOT_VERIFIED,
    CONTRIBUTION_AUTHORIZATION_NOT_FOUND,
    RESULT_ENCRYPTION_FAILED,
    RESULT_LINK_MISSING,

    // timeout
    CONTRIBUTION_TIMEOUT,
    REVEAL_TIMEOUT,
    // AFTER_DEADLINE,

    ABORTED_BY_WORKER,
    CANNOT_REVEAL,
}
